title: Nathan
description: "Class of 2025"
owner_name: Nathan Tejidor
github_username: NathanTejidor
github_repo: "NathanT_2025" 
baseurl: "/NathanT_2025"
future: true
# remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/calculator.md
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/MyJourney.md
  - README4YML.md
  - navigation/snake.md
